FROM python:3.10

RUN mkdir /api

WORKDIR /api

RUN apt-get update
RUN apt install -y libgl1-mesa-glx

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host=0.0.0.0", "--port=8000"]